import { Layout } from "@/components/layout/Layout";
import { motion } from "framer-motion";
import { AlertTriangle } from "lucide-react";
import { SEO } from "@/components/SEO";

const SECTIONS = [
  {
    title: "1. General Information Only",
    content: `The content published on the JCTM Digital Sanctuary (jctm.org.ng) is provided for general informational, spiritual edification, and ministry purposes only. While every effort is made to ensure the accuracy and completeness of the information presented, Jesus Christ Temple Ministry (JCTM) makes no representations or warranties of any kind, express or implied, regarding the completeness, accuracy, reliability, suitability, or availability of any information, teaching, or material on this platform.`,
  },
  {
    title: "2. Spiritual & Doctrinal Content",
    content: `All sermons, teachings, devotionals, and doctrinal content published on this platform represent the beliefs and positions of Jesus Christ Temple Ministry and Prophet Amos Evomobor. These teachings are offered for edification and spiritual growth. They are not a substitute for personal Bible study, pastoral guidance, or direct spiritual counsel. JCTM encourages all believers to study the Scriptures for themselves (Acts 17:11).`,
  },
  {
    title: "3. AI-Generated Content (TempleBots)",
    content: `TempleBots is an AI-powered ministry assistant. Responses generated by TempleBots are produced by artificial intelligence and may not perfectly represent the official doctrinal position of JCTM or Prophet Amos Evomobor. AI responses should not be treated as authoritative pastoral counsel. Always verify theological content against Scripture and consult qualified ministry leadership for matters of serious spiritual concern.`,
  },
  {
    title: "4. Financial & Giving Information",
    content: `Information regarding online giving, tithes, and offerings on this platform is provided for the purpose of facilitating voluntary ministry support. JCTM does not guarantee specific spiritual or material outcomes as a result of giving. All financial transactions are processed by third-party providers (Paystack and Stripe); JCTM is not responsible for errors or outages on these third-party platforms. Always retain your transaction confirmation for your records.`,
  },
  {
    title: "5. External Links",
    content: `The JCTM Digital Sanctuary may contain links to external websites, YouTube videos, and third-party resources. These links are provided for convenience and informational purposes only. JCTM does not endorse, control, or accept responsibility for the content of any external website or platform. Visiting external links is done entirely at your own risk.`,
  },
  {
    title: "6. Advertising Content",
    content: `This website displays advertisements served through Google AdSense (Publisher ID: ca-pub-9869546801865196). Advertisements appearing on this platform are served by Google and do not constitute endorsement by JCTM of any advertised product, service, or organisation. Advertising revenue supports the operational costs of the JCTM Digital Sanctuary and Temple TV ministry broadcasts. JCTM is not responsible for the content of any third-party advertisements displayed on this platform.`,
  },
  {
    title: "7. Medical, Legal & Professional Advice",
    content: `Nothing on the JCTM Digital Sanctuary constitutes medical, legal, financial, or professional advice of any kind. Any prayer requests, testimonies, or content touching on health, legal matters, or personal circumstances is shared for spiritual purposes only. Always consult a qualified professional for matters requiring medical, legal, or financial expertise.`,
  },
  {
    title: "8. Platform Availability",
    content: `JCTM strives to maintain uninterrupted access to the Digital Sanctuary. However, we do not guarantee that the platform will be available at all times. The platform may be temporarily unavailable due to maintenance, server issues, or circumstances beyond our control. JCTM accepts no liability for any inconvenience or loss resulting from platform downtime or technical failures.`,
  },
  {
    title: "9. Limitation of Liability",
    content: `To the maximum extent permitted by applicable law, Jesus Christ Temple Ministry shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of — or inability to use — the JCTM Digital Sanctuary, including reliance on any information, AI-generated content, or materials published herein.`,
  },
  {
    title: "10. Governing Jurisdiction",
    content: `This disclaimer is governed by the laws of the Federal Republic of Nigeria. Any disputes relating to the use of the JCTM Digital Sanctuary shall be subject to the exclusive jurisdiction of the courts of Delta State, Nigeria.`,
  },
];

export default function Disclaimer() {
  return (
    <Layout>
      <SEO
        title="Disclaimer — JCTM Digital Sanctuary"
        description="Disclaimer for the JCTM Digital Sanctuary — Jesus Christ Temple Ministry, Warri Nigeria. Read our disclaimer regarding spiritual content, AI tools, advertising, and liability."
        path="/disclaimer"
        keywords="JCTM disclaimer, Jesus Christ Temple Ministry disclaimer, spiritual content disclaimer, AI tools disclaimer"
        type="website"
        jsonLd={{
          "@context": "https://schema.org",
          "@type": "WebPage",
          "@id": "https://jctm.org.ng/disclaimer#webpage",
          "name": "Disclaimer — JCTM Digital Sanctuary",
          "description": "Disclaimer for the JCTM Digital Sanctuary regarding spiritual content, AI tools, advertising, and liability.",
          "url": "https://jctm.org.ng/disclaimer",
          "inLanguage": "en-NG",
          "isPartOf": { "@id": "https://jctm.org.ng/#website" },
          "publisher": { "@id": "https://jctm.org.ng/#organization" },
          "breadcrumb": {
            "@type": "BreadcrumbList",
            "itemListElement": [
              { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://jctm.org.ng/" },
              { "@type": "ListItem", "position": 2, "name": "Disclaimer", "item": "https://jctm.org.ng/disclaimer" }
            ]
          }
        }}
      />
      <div className="container mx-auto px-4 py-16 max-w-3xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <div className="flex items-center gap-3 mb-3">
            <span className="inline-flex items-center justify-center h-10 w-10 rounded-xl bg-amber-500/15 text-amber-500">
              <AlertTriangle className="h-5 w-5" />
            </span>
            <span className="text-xs font-bold uppercase tracking-[0.2em] text-muted-foreground">Legal</span>
          </div>
          <h1 className="text-3xl md:text-4xl font-bold font-serif text-primary mb-3">Disclaimer</h1>
          <p className="text-muted-foreground mb-2 text-sm">Jesus Christ Temple Ministry (JCTM) · jctm.org.ng</p>
          <p className="text-muted-foreground text-sm mb-10">Last updated: May 2025</p>

          <div className="space-y-8">
            {SECTIONS.map((section, i) => (
              <motion.div
                key={section.title}
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: i * 0.05 }}
                className="rounded-2xl border border-border/60 bg-card/50 p-6"
              >
                <h2 className="font-semibold text-primary mb-3 text-base">{section.title}</h2>
                <p className="text-muted-foreground text-sm leading-relaxed whitespace-pre-line">
                  {section.content}
                </p>
              </motion.div>
            ))}
          </div>

          <p className="mt-10 text-xs text-muted-foreground text-center">
            For questions regarding this disclaimer, contact us at{" "}
            <a href="mailto:info@jctm.org.ng" className="underline hover:text-primary transition-colors">
              info@jctm.org.ng
            </a>
          </p>
        </motion.div>
      </div>
    </Layout>
  );
}
