import { pool } from "@workspace/db";
import { logger } from "./logger.js";

type MinistryArticle = {
  slug: string;
  title: string;
  scripture: string;
  introduction: string;
  sections: Array<{ heading: string; body: string }>;
  lessons: string[];
  prayer: string;
  conclusion: string;
  topic: string;
  category: string;
  tags: string[];
  excerpt: string;
  seoTitle: string;
  seoDescription: string;
  featured?: boolean;
};

const BASE_URL = "https://jctm.org.ng";
const AUTHOR = "Jesus Christ Temple Ministry";

const articles: MinistryArticle[] = [
  {
    slug: "repentance-that-restores-the-heart-to-god",
    title: "Repentance That Restores the Heart to God",
    scripture: "Acts 3:19; Joel 2:12-13",
    introduction: "Repentance is not religious regret; it is a holy turning of the heart back to God. In every generation the Lord raises a voice to call His people away from sin, compromise, and empty worship into a life that bears visible fruit.",
    sections: [
      { heading: "Repentance Begins With Honest Conviction", body: "The Spirit of God first exposes what the heart has tolerated. True repentance does not defend wrong patterns, blame others, or decorate disobedience with religious language. It agrees with God and allows His word to judge every hidden motive." },
      { heading: "Repentance Produces a Changed Direction", body: "Biblical repentance is proven by movement. A believer who has turned to God begins to leave the old road, old appetite, old pride, and old rebellion. The grace of God empowers a new walk, not a polished version of the old one." },
      { heading: "Repentance Opens the Door to Refreshing", body: "Acts 3:19 connects repentance with seasons of refreshing from the presence of the Lord. Where sin is confessed and forsaken, the soul recovers clarity, prayer regains fire, and worship becomes alive again." },
    ],
    lessons: ["Godly sorrow must lead to transformation.", "Repentance is a gift that protects the soul from judgment.", "The fruit of repentance is seen in obedience, humility, and restitution.", "A repentant church becomes a vessel of revival."],
    prayer: "Father, search my heart and remove every way of rebellion. Give me grace to turn fully to You, obey Your word, and walk in the refreshing of Your presence.",
    conclusion: "The ministry of correction is not condemnation; it is mercy calling the soul back before it is too late. Return to the Lord with all your heart and let Him restore what sin has damaged.",
    topic: "repentance",
    category: "Teachings",
    tags: ["repentance", "salvation", "restoration", "holiness"],
    excerpt: "A clear teaching on biblical repentance as a heart-level turning that restores fellowship, obedience, and spiritual refreshing.",
    seoTitle: "Biblical Repentance That Restores the Heart",
    seoDescription: "Learn how true repentance restores the heart to God through conviction, changed direction, obedience, and spiritual refreshing.",
    featured: true,
  },
  {
    slug: "salvation-by-grace-that-produces-holy-living",
    title: "Salvation by Grace That Produces Holy Living",
    scripture: "Titus 2:11-14; Ephesians 2:8-10",
    introduction: "Grace is the saving power of God, but it is never permission to continue in sin. The same grace that forgives also teaches, trains, and separates a people unto good works.",
    sections: [
      { heading: "Grace Saves the Helpless", body: "No man can purchase salvation through works, emotion, tradition, or religious title. The sinner is saved by grace through faith in Jesus Christ, and this salvation is received with humility and gratitude." },
      { heading: "Grace Teaches the Saved", body: "Titus declares that grace teaches us to deny ungodliness. If a message of grace leaves a person comfortable in sin, it has been divorced from Scripture. The true gospel rescues and reforms." },
      { heading: "Grace Creates a Zealous People", body: "Christ gave Himself to purify a peculiar people zealous for good works. The evidence of grace is not lawlessness but a life increasingly yielded to the Lordship of Jesus." },
    ],
    lessons: ["Grace is free, but it is not fruitless.", "Good works do not purchase salvation; they testify that salvation is alive.", "Holiness is the training ground of grace.", "A saved life should become a witness to the saving Christ."],
    prayer: "Lord Jesus, thank You for saving me by grace. Train my heart to reject ungodliness and to live as Your redeemed vessel in this present world.",
    conclusion: "Enterprise ministry content must preserve the balance of the gospel: salvation is by grace alone, and grace produces a holy people for God's glory.",
    topic: "salvation",
    category: "Bible Studies",
    tags: ["grace", "salvation", "holiness", "gospel"],
    excerpt: "A Bible study on saving grace that forgives the sinner and trains the believer into holy living.",
    seoTitle: "Salvation by Grace and Holy Living",
    seoDescription: "Understand biblical grace as the power that saves, teaches, purifies, and produces holy living in every believer.",
    featured: true,
  },
  {
    slug: "faith-and-endurance-when-the-battle-is-long",
    title: "Faith and Endurance When the Battle Is Long",
    scripture: "Hebrews 10:35-39; James 1:2-4",
    introduction: "Many believers can rejoice when victory comes quickly, but mature faith is proven when obedience must continue through delay, pressure, and contradiction.",
    sections: [
      { heading: "Faith Must Not Cast Away Confidence", body: "Hebrews warns believers not to throw away their confidence. The enemy often attacks expectation before he attacks possession. Guard your confidence in God's character even before circumstances change." },
      { heading: "Endurance Is Spiritual Formation", body: "Trials are not wasted when they drive the believer deeper into prayer, patience, and dependence. God uses pressure to mature what comfort cannot produce." },
      { heading: "The Just Shall Live by Faith", body: "Faith is not only a moment of receiving; it is a lifestyle of continuing. The righteous man lives by trusting God's word above what the eyes can measure." },
    ],
    lessons: ["Delay is not denial when God is forming endurance.", "Faith must be guarded through prayer and the word.", "Pressure exposes whether confidence is rooted in God or in outcomes.", "Endurance prepares the believer for weightier assignments."],
    prayer: "Father, strengthen my faith in long seasons. Keep me from drawing back, and teach me to endure until Your will is fulfilled in my life.",
    conclusion: "Enduring faith is a sermon the world can read. Continue in obedience, because the Lord who promised is faithful.",
    topic: "faith",
    category: "Devotionals",
    tags: ["faith", "endurance", "trials", "perseverance"],
    excerpt: "A devotional article helping believers remain steady in faith when spiritual battles and delays are prolonged.",
    seoTitle: "Faith and Endurance in Long Battles",
    seoDescription: "Strengthen your faith during long seasons with biblical teaching on endurance, confidence, and perseverance.",
    featured: true,
  },
  {
    slug: "holiness-is-still-the-beauty-of-the-church",
    title: "Holiness Is Still the Beauty of the Church",
    scripture: "Hebrews 12:14; 1 Peter 1:15-16",
    introduction: "Holiness is not an outdated church word. It is the beauty, boundary, and testimony of a people who belong to a holy God.",
    sections: [
      { heading: "Holiness Begins With God's Nature", body: "The command to be holy is rooted in who God is. The church does not define holiness by culture, fashion, or convenience; she receives it from the character of the Lord." },
      { heading: "Holiness Touches the Whole Life", body: "True holiness affects speech, business, relationships, entertainment, giving, worship, and private thoughts. It refuses the divided life where Sunday devotion hides weekday compromise." },
      { heading: "Holiness Protects Spiritual Sight", body: "Hebrews connects holiness with seeing the Lord. A compromised life dulls discernment, but a consecrated life becomes sensitive to God's presence and correction." },
    ],
    lessons: ["Holiness is relational separation unto God.", "A church without holiness loses spiritual authority.", "Private purity strengthens public ministry.", "Grace empowers holiness rather than replacing it."],
    prayer: "Holy Father, make my life pleasing to You. Purify my desires, speech, and decisions until my whole life reflects Your nature.",
    conclusion: "The world does not need a church that looks like itself. It needs a holy church that reveals the beauty and authority of Christ.",
    topic: "holiness",
    category: "Teachings",
    tags: ["holiness", "righteousness", "consecration", "christian-living"],
    excerpt: "A sermon-inspired teaching on holiness as the enduring beauty, boundary, and authority of the church.",
    seoTitle: "Holiness Is Still the Beauty of the Church",
    seoDescription: "Explore why holiness remains essential for Christian living, spiritual authority, and seeing the Lord.",
  },
  {
    slug: "prayer-that-prevails-in-spiritual-warfare",
    title: "Prayer That Prevails in Spiritual Warfare",
    scripture: "Ephesians 6:10-18; Luke 18:1",
    introduction: "Prayer is not a religious accessory; it is the believer's lifeline in a real spiritual conflict. A praying church remains alert, clothed, and victorious.",
    sections: [
      { heading: "Prevailing Prayer Starts With Strength in the Lord", body: "Ephesians begins spiritual warfare with the command to be strong in the Lord. The believer does not fight from human anger or noise, but from union with Christ and submission to His authority." },
      { heading: "The Whole Armor Must Be Worn", body: "Truth, righteousness, peace, faith, salvation, and the word of God are not optional pieces. Prayer without obedience leaves gaps; obedience without prayer becomes self-reliance." },
      { heading: "Watchfulness Keeps Prayer Accurate", body: "Paul commands believers to watch with perseverance. Watchful prayer discerns patterns, resists deception, and refuses spiritual sleep." },
    ],
    lessons: ["Spiritual warfare requires both authority and submission.", "Prayer must be joined with truth and righteousness.", "Persistence is part of victory.", "A watchful believer is harder to deceive."],
    prayer: "Lord, teach my hands to war and my heart to remain humble. Clothe me with Your armor and make my prayer life steady, discerning, and fruitful.",
    conclusion: "The battle is real, but Christ is greater. Build a disciplined prayer altar and stand firm until the will of God prevails.",
    topic: "prayer",
    category: "Teachings",
    tags: ["prayer", "spiritual-warfare", "deliverance", "watchfulness"],
    excerpt: "A practical teaching on prayer, spiritual warfare, watchfulness, and standing strong in the armor of God.",
    seoTitle: "Prayer That Prevails in Spiritual Warfare",
    seoDescription: "Learn how biblical prayer, watchfulness, and the armor of God equip believers to prevail in spiritual warfare.",
  },
  {
    slug: "the-kingdom-of-god-and-the-surrendered-life",
    title: "The Kingdom of God and the Surrendered Life",
    scripture: "Matthew 6:33; Romans 14:17",
    introduction: "The Kingdom of God is not a slogan for ambition; it is the reign of God over surrendered lives. To seek the Kingdom first is to allow God to govern desire, priority, and obedience.",
    sections: [
      { heading: "The Kingdom Demands First Place", body: "Jesus did not say to add the Kingdom to an already crowded life. He commanded believers to seek it first, placing God's will above survival anxiety, status, and personal plans." },
      { heading: "The Kingdom Is Righteousness, Peace, and Joy", body: "Romans reveals the inner evidence of Kingdom life. Where God reigns, righteousness becomes the standard, peace becomes the atmosphere, and joy becomes the strength." },
      { heading: "The Kingdom Produces Visible Allegiance", body: "A surrendered life makes decisions that reveal a different government. The believer's speech, stewardship, forgiveness, and mission all testify that Christ is King." },
    ],
    lessons: ["Kingdom priority reorganizes daily life.", "Surrender is the doorway to Kingdom fruit.", "The Kingdom corrects selfish religion.", "Christ must reign over both public and private choices."],
    prayer: "King Jesus, rule my heart completely. Let Your Kingdom come in my home, work, ministry, and decisions.",
    conclusion: "The church becomes powerful when believers stop using Kingdom language and begin living under Kingdom rule.",
    topic: "kingdom",
    category: "Bible Studies",
    tags: ["kingdom-of-god", "surrender", "obedience", "discipleship"],
    excerpt: "A Bible study on seeking God's Kingdom first through surrender, righteousness, peace, and visible allegiance to Christ.",
    seoTitle: "The Kingdom of God and Surrender",
    seoDescription: "Discover what it means to seek the Kingdom of God first through surrendered priorities and obedient Christian living.",
  },
  {
    slug: "prophetic-warnings-are-mercy-before-judgment",
    title: "Prophetic Warnings Are Mercy Before Judgment",
    scripture: "Amos 3:7; Ezekiel 33:7-9",
    introduction: "A true prophetic warning is not entertainment or fear marketing. It is mercy sounding before judgment arrives, calling people to hear God and return.",
    sections: [
      { heading: "God Reveals Before He Judges", body: "Amos teaches that the Lord reveals His counsel to His servants. Warning is evidence that God is patient, not eager to destroy. He speaks so that people may turn." },
      { heading: "The Watchman Must Speak Faithfully", body: "Ezekiel places weight on the watchman. A minister who sees danger but stays silent has failed the people. Love must sometimes speak with holy urgency." },
      { heading: "The People Must Respond With Obedience", body: "Hearing warning without repentance hardens the heart. The purpose of prophetic speech is not curiosity but correction, alignment, and preservation." },
    ],
    lessons: ["Warnings reveal God's mercy and patience.", "True prophecy calls people back to Scripture.", "A faithful watchman values souls above popularity.", "Delayed judgment should never be mistaken for approval."],
    prayer: "Lord, give me ears to hear Your correction. Keep me from despising warning, and make me quick to obey Your voice.",
    conclusion: "Prophetic ministry is enterprise-grade only when it is accountable to Scripture, driven by love, and aimed at repentance.",
    topic: "prophetic-warnings",
    category: "Prophetic Messages",
    tags: ["prophecy", "warning", "judgment", "mercy"],
    excerpt: "A prophetic teaching explaining why biblical warnings are acts of mercy that call people to repentance before judgment.",
    seoTitle: "Prophetic Warnings as Mercy Before Judgment",
    seoDescription: "Understand biblical prophetic warnings as mercy before judgment and a call to repentance, obedience, and watchfulness.",
  },
  {
    slug: "mercy-that-restores-without-excusing-sin",
    title: "Mercy That Restores Without Excusing Sin",
    scripture: "John 8:10-11; Micah 7:18-19",
    introduction: "God's mercy is deep enough to lift the fallen, but holy enough to tell them to sin no more. Biblical mercy restores the person without negotiating with bondage.",
    sections: [
      { heading: "Mercy Meets People in Their Shame", body: "Jesus did not deny the woman's failure, yet He refused to let condemnation have the final word. Mercy reaches people where sin has exposed them." },
      { heading: "Mercy Commands a New Walk", body: "The words 'go and sin no more' show that mercy is not passive tolerance. Mercy creates a future of obedience and dignity." },
      { heading: "Mercy Triumphs Through Truth", body: "When truth and mercy are separated, people are either crushed or deceived. In Christ they meet perfectly, healing the sinner and confronting the sin." },
    ],
    lessons: ["Mercy is not weakness; it is redemptive strength.", "Restoration includes a call to holiness.", "Condemnation cannot heal what truth-filled mercy can restore.", "The church must carry both compassion and correction."],
    prayer: "Merciful Father, restore me where I have fallen and teach me to walk in truth. Make me a vessel of mercy that never compromises holiness.",
    conclusion: "The ministry of Jesus shows a better way than harsh religion or careless tolerance: mercy that restores and truth that frees.",
    topic: "mercy",
    category: "Devotionals",
    tags: ["mercy", "redemption", "restoration", "truth"],
    excerpt: "A devotional on biblical mercy that restores sinners while calling them into truth, dignity, and holiness.",
    seoTitle: "Mercy That Restores Without Excusing Sin",
    seoDescription: "Explore biblical mercy that heals shame, restores dignity, and calls believers to walk in holiness and truth.",
  },
  {
    slug: "end-times-awareness-without-fear",
    title: "End Times Awareness Without Fear",
    scripture: "Matthew 24:4-14; 1 Thessalonians 5:1-8",
    introduction: "End-times teaching should awaken the church, not paralyze it. Jesus called His people to watchfulness, endurance, purity, and mission until the end.",
    sections: [
      { heading: "Discernment Protects Against Deception", body: "The first warning Jesus gave about the last days was not earthquakes but deception. A Bible-grounded believer is not easily moved by rumors, personalities, or spiritual confusion." },
      { heading: "Watchfulness Is Not Panic", body: "Paul calls believers children of light. The watchful church is sober, prayerful, and prepared, not driven by fear or speculation." },
      { heading: "Mission Continues Until the End", body: "Matthew 24 connects the end with the preaching of the gospel. Awareness of the times should increase evangelism, holiness, and compassion." },
    ],
    lessons: ["End-time teaching must produce readiness, not fear.", "Scripture is the believer's safeguard against deception.", "A watching church must also be a witnessing church.", "Hope in Christ is stronger than global shaking."],
    prayer: "Lord Jesus, make me watchful and sober. Deliver me from fear and deception, and use my life to testify of Your gospel in these times.",
    conclusion: "The end-time believer is not helpless. In Christ, we watch, pray, endure, and shine as children of light.",
    topic: "end-times",
    category: "Bible Studies",
    tags: ["end-times", "watchfulness", "discernment", "hope"],
    excerpt: "A balanced Bible study on end-times awareness that produces watchfulness, mission, and hope instead of fear.",
    seoTitle: "End Times Awareness Without Fear",
    seoDescription: "Learn how believers can understand end-times teaching with biblical discernment, watchfulness, mission, and hope.",
  },
  {
    slug: "worship-that-god-receives",
    title: "Worship That God Receives",
    scripture: "John 4:23-24; Romans 12:1",
    introduction: "Worship is more than music and atmosphere. The Father seeks worshippers whose hearts, bodies, and obedience are offered in spirit and truth.",
    sections: [
      { heading: "True Worship Begins in Truth", body: "Jesus said worship must be in spirit and truth. Sincerity alone is not enough if truth is absent. The word of God must govern the worship we bring." },
      { heading: "True Worship Offers the Whole Life", body: "Romans calls the body a living sacrifice. Worship includes how we live, serve, forgive, speak, and handle temptation when no song is playing." },
      { heading: "True Worship Draws Near With Reverence", body: "Intimacy with God never removes reverence. The closer the heart comes to the Lord, the more it honors His holiness and responds with humility." },
    ],
    lessons: ["God seeks worshippers, not performers.", "Truth protects worship from emotional deception.", "Daily obedience is worship.", "Intimacy and reverence must remain together."],
    prayer: "Father, make me a true worshipper. Let my songs, choices, body, and service become a living sacrifice before You.",
    conclusion: "A ministry platform may carry many songs, but the real sound God receives is a surrendered life worshipping in spirit and truth.",
    topic: "worship",
    category: "Devotionals",
    tags: ["worship", "intimacy", "truth", "surrender"],
    excerpt: "A devotional teaching on worship in spirit and truth as a whole-life offering that God receives.",
    seoTitle: "Worship That God Receives",
    seoDescription: "Discover biblical worship in spirit and truth through reverence, surrender, obedience, and intimacy with God.",
  },
  {
    slug: "leadership-that-serves-the-flock",
    title: "Leadership That Serves the Flock",
    scripture: "1 Peter 5:1-4; Mark 10:42-45",
    introduction: "Ministry leadership is not a platform for control. It is a sacred stewardship to serve, feed, guard, and model Christ before the flock.",
    sections: [
      { heading: "Leaders Must Shepherd Willingly", body: "Peter instructs elders to shepherd willingly, not by compulsion or selfish gain. The heart of a minister must be purified from ambition that uses people." },
      { heading: "Leaders Must Reject Domination", body: "Jesus contrasted Kingdom leadership with worldly power. The minister leads by service, example, sacrifice, and truth, not by intimidation." },
      { heading: "Leaders Answer to the Chief Shepherd", body: "Every under-shepherd must remember that the flock belongs to Christ. Accountability to the Chief Shepherd keeps leadership humble and careful." },
    ],
    lessons: ["Leadership is stewardship before God.", "Authority in ministry must be shaped by service.", "The flock belongs to Christ, not the minister.", "Healthy leaders model what they teach."],
    prayer: "Chief Shepherd, purify every leader in Your church. Make us servants who feed, guard, and guide Your people with humility and truth.",
    conclusion: "Enterprise ministry growth must never outgrow Christlike leadership. The stronger the platform, the deeper the servant heart must become.",
    topic: "leadership",
    category: "Ministry Insights",
    tags: ["leadership", "ministry", "service", "shepherding"],
    excerpt: "A ministry insight article on Christlike leadership that serves the flock with humility, truth, and accountability.",
    seoTitle: "Leadership That Serves the Flock",
    seoDescription: "Explore biblical ministry leadership as servant-hearted stewardship under the authority of Christ the Chief Shepherd.",
  },
  {
    slug: "righteousness-in-an-unrighteous-generation",
    title: "Righteousness in an Unrighteous Generation",
    scripture: "Psalm 15; Matthew 5:6",
    introduction: "Righteousness is not only a doctrine to confess; it is a hunger to live rightly before God in a generation that normalizes compromise.",
    sections: [
      { heading: "Righteousness Begins With Hunger", body: "Jesus blessed those who hunger and thirst for righteousness. The righteous life grows where the heart desires God's approval more than cultural acceptance." },
      { heading: "Righteousness Governs Conduct", body: "Psalm 15 describes truthfulness, integrity, clean speech, and faithful promises. Righteousness must become visible in ordinary decisions." },
      { heading: "Righteousness Carries Witness", body: "A righteous believer becomes a quiet rebuke to darkness and a living invitation to the Kingdom. The world may resist it, but heaven honors it." },
    ],
    lessons: ["Righteousness must be desired before it is demonstrated.", "Integrity is worship in practical form.", "Compromise weakens witness.", "God sustains those who choose righteousness."],
    prayer: "Lord, give me a hunger for righteousness. Strengthen my integrity and help me stand clean in an unclean generation.",
    conclusion: "The church's voice becomes weighty when its life becomes righteous. Let righteousness return to the center of Christian witness.",
    topic: "righteousness",
    category: "Teachings",
    tags: ["righteousness", "integrity", "holiness", "witness"],
    excerpt: "A teaching on living righteously with integrity, clean speech, and strong witness in a compromising generation.",
    seoTitle: "Righteousness in an Unrighteous Generation",
    seoDescription: "Learn how believers can live with righteousness, integrity, and spiritual witness in a generation of compromise.",
  },
  {
    slug: "forgiveness-and-the-freedom-of-the-soul",
    title: "Forgiveness and the Freedom of the Soul",
    scripture: "Matthew 6:14-15; Colossians 3:13",
    introduction: "Forgiveness is not pretending that pain was harmless. It is releasing the debt to God so the soul can be free from bitterness and bondage.",
    sections: [
      { heading: "Forgiveness Obeys the Mercy We Have Received", body: "Jesus ties forgiveness to the reality of being forgiven. A person who has received mercy must not become a prison for another person's debt." },
      { heading: "Forgiveness Breaks Bitterness", body: "Unforgiveness keeps the wound active. Forgiveness does not always restore trust immediately, but it removes the poison that bitterness releases inside the heart." },
      { heading: "Forgiveness Requires Grace and Wisdom", body: "Some offenses require boundaries, counsel, and time. Forgiveness is not foolish exposure to abuse; it is a spiritual release governed by truth and wisdom." },
    ],
    lessons: ["Forgiveness is obedience, not emotion alone.", "Bitterness damages the carrier first.", "Boundaries can coexist with forgiveness.", "The cross gives strength to release offense."],
    prayer: "Father, help me forgive as You have forgiven me. Heal my wounded places and deliver my heart from bitterness.",
    conclusion: "A free soul worships differently. Let forgiveness open the prison door and allow the peace of Christ to rule again.",
    topic: "forgiveness",
    category: "Devotionals",
    tags: ["forgiveness", "healing", "freedom", "mercy"],
    excerpt: "A devotional reflection on forgiveness as obedience, healing, and freedom from bitterness through the mercy of Christ.",
    seoTitle: "Forgiveness and Freedom of the Soul",
    seoDescription: "Understand biblical forgiveness as a path to healing, freedom from bitterness, and deeper obedience to Christ.",
  },
  {
    slug: "the-word-of-god-as-the-believers-anchor",
    title: "The Word of God as the Believer's Anchor",
    scripture: "2 Timothy 3:16-17; Psalm 119:105",
    introduction: "In seasons of confusion, emotion, and spiritual noise, the word of God remains the anchor that steadies the believer and equips the church.",
    sections: [
      { heading: "Scripture Corrects and Trains", body: "Paul teaches that all Scripture is profitable for doctrine, reproof, correction, and instruction. A mature church welcomes the word even when it confronts." },
      { heading: "Scripture Gives Light for Daily Steps", body: "Psalm 119 calls the word a lamp and light. God often leads not by showing the whole road, but by giving enough light for obedient next steps." },
      { heading: "Scripture Equips the Servant of God", body: "The word does not merely inform; it furnishes the believer for every good work. Ministry without Scripture becomes personality-driven and unstable." },
    ],
    lessons: ["The Bible must judge every doctrine and experience.", "Correction is part of Scripture's love.", "Daily guidance comes through the word.", "A word-filled church becomes stable and fruitful."],
    prayer: "Lord, anchor my life in Your word. Give me hunger for Scripture and humility to obey every correction it brings.",
    conclusion: "A ministry blog can only serve the church if it sends readers back to Scripture. Let the word remain final.",
    topic: "scripture",
    category: "Bible Studies",
    tags: ["bible-study", "scripture", "doctrine", "discipleship"],
    excerpt: "A Bible study on Scripture as the believer's anchor for doctrine, correction, guidance, and ministry fruitfulness.",
    seoTitle: "The Word of God as the Believer's Anchor",
    seoDescription: "Explore how Scripture anchors believers through doctrine, correction, daily guidance, and spiritual maturity.",
  },
  {
    slug: "obedience-is-better-than-religious-noise",
    title: "Obedience Is Better Than Religious Noise",
    scripture: "1 Samuel 15:22; John 14:15",
    introduction: "God is not impressed by activity that masks disobedience. The Lord receives worship, service, and sacrifice when they flow from a heart that obeys Him.",
    sections: [
      { heading: "Sacrifice Cannot Replace Obedience", body: "Saul tried to preserve religious appearance while violating God's command. Samuel's response remains a warning: obedience is better than sacrifice." },
      { heading: "Love for Christ Is Proven by Obedience", body: "Jesus said, 'If ye love me, keep my commandments.' Love is more than emotion in worship; it is surrender in decisions." },
      { heading: "Obedience Carries Spiritual Authority", body: "A believer who obeys God carries a quiet authority because heaven can trust surrendered vessels. Disobedience weakens even loud ministry." },
    ],
    lessons: ["God values obedience above performance.", "Partial obedience is still rebellion when God has spoken clearly.", "Love must become obedience.", "Spiritual authority grows in surrendered lives."],
    prayer: "Lord, remove every religious excuse from my heart. Teach me to obey quickly, fully, and joyfully.",
    conclusion: "The church does not need louder noise; it needs deeper obedience. When obedience returns, worship regains weight.",
    topic: "obedience",
    category: "Teachings",
    tags: ["obedience", "worship", "surrender", "discipleship"],
    excerpt: "A teaching on why God receives obedience above religious performance, noise, and partial surrender.",
    seoTitle: "Obedience Is Better Than Religious Noise",
    seoDescription: "Learn why biblical obedience matters more than religious activity and how surrender restores spiritual authority.",
  },
  {
    slug: "discernment-for-a-confused-generation",
    title: "Discernment for a Confused Generation",
    scripture: "1 John 4:1; Hebrews 5:14",
    introduction: "Discernment is essential in a generation where spiritual language is often mixed with deception. Believers must test every spirit and mature through practiced obedience.",
    sections: [
      { heading: "Not Every Voice Is From God", body: "John commands believers to test the spirits. The presence of spiritual words, miracles, or confidence does not automatically prove divine origin." },
      { heading: "Discernment Matures Through Use", body: "Hebrews says mature believers have senses trained by reason of use. Discernment grows when Scripture, prayer, and obedience shape repeated decisions." },
      { heading: "Discernment Protects Love and Truth", body: "True discernment is not suspicion toward everyone. It protects the church so love can remain pure and truth can remain central." },
    ],
    lessons: ["Every message must be tested by Scripture.", "Maturity trains spiritual senses.", "Discernment without love becomes pride.", "Love without discernment becomes vulnerable."],
    prayer: "Holy Spirit, sharpen my discernment. Keep me humble, biblical, and watchful in a confused generation.",
    conclusion: "The end-time church must not be gullible or cynical. She must be discerning, loving, and grounded in truth.",
    topic: "discernment",
    category: "Prophetic Messages",
    tags: ["discernment", "false-teaching", "truth", "watchfulness"],
    excerpt: "A prophetic teaching on testing spirits, training discernment, and staying grounded in Scripture amid confusion.",
    seoTitle: "Discernment for a Confused Generation",
    seoDescription: "Build biblical discernment by testing every spirit, maturing through Scripture, and protecting truth with love.",
  },
  {
    slug: "revival-begins-with-a-corrected-altar",
    title: "Revival Begins With a Corrected Altar",
    scripture: "1 Kings 18:30-39; Psalm 85:6",
    introduction: "Before fire fell on Carmel, Elijah repaired the altar of the Lord. Revival often begins not with noise, but with correction, restoration, and surrendered worship.",
    sections: [
      { heading: "The Broken Altar Must Be Repaired", body: "An altar represents worship, covenant, and surrender. When the altar is broken, people may still gather, but the spiritual center has been damaged." },
      { heading: "Correction Prepares the Place of Fire", body: "Elijah did not call for fire over disorder. He restored the altar first. God honors consecrated order before visible demonstration." },
      { heading: "Revival Reveals the True God", body: "When fire fell, the people confessed, 'The Lord, He is the God.' True revival does not glorify a man; it restores the fear and knowledge of God." },
    ],
    lessons: ["Revival requires repaired worship and restored covenant.", "Correction is preparation, not punishment.", "Fire falls where God is honored in truth.", "True revival turns attention back to the Lord."],
    prayer: "Lord, repair every broken altar in my life and in Your church. Send revival that restores Your fear, truth, and glory.",
    conclusion: "A corrected altar is the foundation of lasting revival. Let worship, doctrine, and surrender be repaired so the fire of God can rest.",
    topic: "revival",
    category: "Prophetic Messages",
    tags: ["revival", "altar", "correction", "fire-of-god"],
    excerpt: "A prophetic message on how correction, repaired altars, and surrendered worship prepare the church for true revival.",
    seoTitle: "Revival Begins With a Corrected Altar",
    seoDescription: "Discover why true revival begins with altar repair, correction, consecration, and the restoration of God's glory.",
  },
  {
    slug: "the-cross-and-the-cost-of-discipleship",
    title: "The Cross and the Cost of Discipleship",
    scripture: "Luke 9:23; Galatians 2:20",
    introduction: "Discipleship is not admiration from a distance. Jesus calls every follower to deny self, take up the cross daily, and follow Him.",
    sections: [
      { heading: "Self-Denial Is the Entrance", body: "The first demand of discipleship is not public ministry but self-denial. The believer must surrender the throne of personal will to Christ." },
      { heading: "The Cross Is Daily", body: "Jesus said daily. Discipleship is not a one-time emotional response but a continual death to sin, pride, revenge, and selfish ambition." },
      { heading: "Christ Lives Through the Crucified Life", body: "Paul's testimony reveals the fruit of the cross: 'Christ liveth in me.' The surrendered believer becomes a vessel through whom Christ is expressed." },
    ],
    lessons: ["Discipleship requires self-denial.", "The cross confronts selfish ambition.", "Daily surrender forms Christlike character.", "A crucified life carries resurrection power."],
    prayer: "Lord Jesus, teach me to deny myself and follow You daily. Let Your life be seen through my surrendered life.",
    conclusion: "A church that preaches the cross must also live the cross. True discipleship remains the pathway to authentic spiritual power.",
    topic: "discipleship",
    category: "Bible Studies",
    tags: ["cross", "discipleship", "self-denial", "christian-living"],
    excerpt: "A Bible study on the cost of discipleship, daily self-denial, and the crucified life that reveals Christ.",
    seoTitle: "The Cross and the Cost of Discipleship",
    seoDescription: "Understand Jesus' call to self-denial, daily cross-bearing, and surrendered discipleship that reveals Christ.",
  },
  {
    slug: "family-altars-and-generational-faith",
    title: "Family Altars and Generational Faith",
    scripture: "Deuteronomy 6:6-7; Joshua 24:15",
    introduction: "Faith must not live only in church gatherings. God desires homes where His word is taught, prayer is practiced, and the next generation sees living faith.",
    sections: [
      { heading: "The Word Must Be Taught at Home", body: "Deuteronomy places instruction in daily family rhythms. Parents and guardians must turn ordinary moments into discipleship opportunities." },
      { heading: "Prayer Builds a Spiritual Atmosphere", body: "A family altar does not need performance; it needs consistency. Regular prayer changes the atmosphere and teaches children dependence on God." },
      { heading: "Families Must Choose Whom They Serve", body: "Joshua's declaration shows leadership in the home. A godly household makes clear decisions about worship, values, and spiritual direction." },
    ],
    lessons: ["Home is a primary discipleship ground.", "Small consistent altars shape lasting faith.", "Children learn by seeing lived Christianity.", "Families must intentionally choose the Lord."],
    prayer: "Lord, establish my home as an altar of prayer, Scripture, love, and obedience. Let generational faith arise.",
    conclusion: "A strong ministry platform should strengthen homes. Let every household become a small sanctuary where Christ is honored.",
    topic: "family",
    category: "Ministry Insights",
    tags: ["family", "prayer", "discipleship", "children"],
    excerpt: "A ministry insight on building family altars through prayer, Scripture, and intentional generational discipleship.",
    seoTitle: "Family Altars and Generational Faith",
    seoDescription: "Learn how families can build spiritual altars through prayer, Scripture, and intentional discipleship at home.",
  },
  {
    slug: "giving-with-a-clean-heart-before-god",
    title: "Giving With a Clean Heart Before God",
    scripture: "2 Corinthians 9:6-8; Matthew 6:1-4",
    introduction: "Christian giving is worship, not manipulation. God loves cheerful, clean-hearted generosity that flows from faith, gratitude, and compassion.",
    sections: [
      { heading: "Giving Must Be Free From Performance", body: "Jesus warned against giving to be seen by men. The Father values secret sincerity more than public display." },
      { heading: "Giving Reflects Trust in God's Sufficiency", body: "Paul teaches cheerful generosity because God is able to make grace abound. The giver trusts that obedience and compassion are never wasted before God." },
      { heading: "Giving Should Serve Kingdom Purpose", body: "Biblical giving supports ministry, helps the needy, and honors God. It must never be twisted into greed, pressure, or spiritual trade." },
    ],
    lessons: ["Giving is worship when the heart is clean.", "God values cheerful generosity.", "Kingdom giving must reject manipulation.", "Generosity reflects trust in God's provision."],
    prayer: "Father, purify my motives in giving. Teach me generosity that honors You and serves Your Kingdom with joy.",
    conclusion: "A mature ministry teaches giving with truth and integrity. Let generosity remain worship, not a marketplace.",
    topic: "giving",
    category: "Teachings",
    tags: ["giving", "stewardship", "generosity", "integrity"],
    excerpt: "A balanced teaching on Christian giving as worship, cheerful generosity, and clean-hearted stewardship before God.",
    seoTitle: "Giving With a Clean Heart Before God",
    seoDescription: "Explore biblical giving as worship, cheerful generosity, Kingdom stewardship, and integrity before God.",
  },
  {
    slug: "the-holy-spirit-and-a-life-of-power",
    title: "The Holy Spirit and a Life of Power",
    scripture: "Acts 1:8; Romans 8:13-14",
    introduction: "The Holy Spirit empowers witness, guides sons of God, and brings victory over the flesh. Power without holiness is dangerous; holiness without dependence becomes dry.",
    sections: [
      { heading: "Power Is Given for Witness", body: "Acts 1:8 shows that Spirit empowerment makes believers witnesses. The purpose of power is not self-display but testimony to Christ." },
      { heading: "The Spirit Leads Into Sonship", body: "Romans teaches that those led by the Spirit are sons of God. The Spirit guides believers into obedience, identity, and intimacy with the Father." },
      { heading: "The Spirit Helps Put Sin to Death", body: "The Spirit does not merely give gifts; He empowers mortification of the flesh. A Spirit-filled life should become increasingly free from sin's dominion." },
    ],
    lessons: ["Spirit power is for Christ-centered witness.", "The Spirit leads, not just excites.", "True power agrees with holiness.", "Dependence on the Spirit is daily Christian life."],
    prayer: "Holy Spirit, fill me, lead me, and empower me to witness for Christ. Put to death every work of the flesh in my life.",
    conclusion: "The church needs the Holy Spirit's power with the Holy Spirit's purity. Both belong together in biblical ministry.",
    topic: "holy-spirit",
    category: "Bible Studies",
    tags: ["holy-spirit", "power", "witness", "sonship"],
    excerpt: "A Bible study on the Holy Spirit's power for witness, sonship, guidance, and victory over the flesh.",
    seoTitle: "The Holy Spirit and a Life of Power",
    seoDescription: "Learn how the Holy Spirit empowers Christian witness, leads believers as sons of God, and strengthens holy living.",
  },
  {
    slug: "spiritual-growth-through-correction",
    title: "Spiritual Growth Through Correction",
    scripture: "Proverbs 3:11-12; Hebrews 12:5-11",
    introduction: "Correction is one of God's tools for producing mature sons and daughters. A heart that rejects correction often rejects the very path of growth.",
    sections: [
      { heading: "Correction Reveals God's Love", body: "Hebrews teaches that the Lord disciplines those He loves. Divine correction is not rejection; it is evidence that God is forming His children." },
      { heading: "Correction Trains Righteousness", body: "No discipline feels pleasant in the moment, but it yields peaceful fruit. Correction trains desires, decisions, and direction." },
      { heading: "Correction Requires a Teachable Spirit", body: "A teachable person can grow quickly because pride does not block truth. The wise receive correction and become wiser still." },
    ],
    lessons: ["Correction is love when it leads to righteousness.", "Pride turns correction into offense.", "A teachable spirit accelerates maturity.", "God corrects to form sons, not destroy them."],
    prayer: "Father, give me a teachable heart. Help me receive Your correction and grow in righteousness, humility, and maturity.",
    conclusion: "The Correction Mandate is not only a message to others; it is a daily invitation for every believer to become teachable before God.",
    topic: "correction",
    category: "Ministry Insights",
    tags: ["correction", "growth", "discipline", "maturity"],
    excerpt: "A ministry insight on how correction trains righteousness, forms maturity, and reveals the Father's love.",
    seoTitle: "Spiritual Growth Through Correction",
    seoDescription: "Understand biblical correction as God's loving tool for maturity, righteousness, humility, and spiritual growth.",
  },
  {
    slug: "evangelism-with-compassion-and-truth",
    title: "Evangelism With Compassion and Truth",
    scripture: "Mark 16:15; 2 Corinthians 5:18-20",
    introduction: "The gospel must be carried with both compassion and truth. Evangelism is not winning arguments; it is representing Christ to people who need reconciliation with God.",
    sections: [
      { heading: "The Command Is Still Go", body: "Jesus commanded the church to preach the gospel to every creature. Digital platforms, local outreaches, and personal witness are all opportunities to obey the same commission." },
      { heading: "The Message Is Reconciliation", body: "Paul calls believers ambassadors of reconciliation. Evangelism announces that God has made a way through Christ for sinners to return." },
      { heading: "The Messenger Must Reflect Christ", body: "Truth without compassion can sound harsh; compassion without truth can become empty. The evangelist must carry the heart and message of Jesus." },
    ],
    lessons: ["The Great Commission remains active.", "Evangelism centers on reconciliation through Christ.", "Compassion and truth must travel together.", "Every believer has a witness field."],
    prayer: "Lord, make me a faithful ambassador. Give me boldness, compassion, and wisdom to share Your gospel with those around me.",
    conclusion: "A global ministry blog should not only inform believers; it should call them into mission. Go with compassion and truth.",
    topic: "evangelism",
    category: "Ministry Insights",
    tags: ["evangelism", "gospel", "mission", "reconciliation"],
    excerpt: "A ministry insight on evangelism that carries the gospel with compassion, truth, and ambassadorial responsibility.",
    seoTitle: "Evangelism With Compassion and Truth",
    seoDescription: "Learn how believers can share the gospel with compassion, truth, boldness, and a heart for reconciliation.",
  },
  {
    slug: "peace-in-the-middle-of-spiritual-storms",
    title: "Peace in the Middle of Spiritual Storms",
    scripture: "Mark 4:35-41; Philippians 4:6-7",
    introduction: "Peace is not the absence of storms; it is the presence and authority of Christ ruling the heart while storms rage around us.",
    sections: [
      { heading: "Jesus Is Present in the Storm", body: "The disciples saw waves and assumed danger had the final word. But Christ was in the boat, and His presence changed the meaning of the storm." },
      { heading: "Prayer Guards the Heart", body: "Philippians teaches believers to bring requests to God with thanksgiving. The result is peace that guards the heart and mind in Christ Jesus." },
      { heading: "Peace Listens to Christ's Authority", body: "Jesus spoke to the storm, and creation obeyed. The believer's peace grows when the authority of Christ becomes greater than the voice of fear." },
    ],
    lessons: ["Christ's presence is stronger than visible trouble.", "Prayer transfers anxiety into God's hands.", "Peace guards the mind from fear's invasion.", "The authority of Jesus is final over every storm."],
    prayer: "Prince of Peace, rule my heart in every storm. Teach me to pray, trust, and rest under Your authority.",
    conclusion: "Storms may be loud, but Christ is Lord. Let His peace guard your heart until the wind becomes still.",
    topic: "peace",
    category: "Devotionals",
    tags: ["peace", "storms", "prayer", "trust"],
    excerpt: "A devotional on finding Christ's peace through prayer, trust, and His authority in the middle of spiritual storms.",
    seoTitle: "Peace in the Middle of Spiritual Storms",
    seoDescription: "Find biblical peace in spiritual storms through Christ's presence, prayer, trust, and the authority of Jesus.",
  },
  {
    slug: "purity-in-thought-speech-and-conduct",
    title: "Purity in Thought, Speech, and Conduct",
    scripture: "Matthew 5:8; Philippians 4:8",
    introduction: "Purity is not limited to outward appearance. It reaches the thoughts we entertain, the words we release, and the conduct we practice.",
    sections: [
      { heading: "Purity Begins in the Heart", body: "Jesus blessed the pure in heart. A clean life begins where only God sees, before it becomes visible where people applaud." },
      { heading: "Purity Disciplines the Mind", body: "Paul instructs believers to think on things that are true, honest, just, pure, lovely, and praiseworthy. The mind must be guarded because thought becomes appetite." },
      { heading: "Purity Shapes Speech and Conduct", body: "A pure heart should produce cleaner words and wiser choices. Speech that wounds, deceives, or corrupts cannot be separated from spiritual formation." },
    ],
    lessons: ["Purity is inward before it is outward.", "The mind must be trained by Scripture.", "Speech reveals the state of the heart.", "Purity increases spiritual sensitivity."],
    prayer: "Lord, purify my heart, thoughts, words, and actions. Let my inner life be pleasing before You.",
    conclusion: "A pure church becomes a clear vessel. Let purity return to the center of discipleship and daily Christian living.",
    topic: "purity",
    category: "Teachings",
    tags: ["purity", "heart", "speech", "conduct"],
    excerpt: "A teaching on biblical purity in the heart, thoughts, speech, and conduct of everyday Christian living.",
    seoTitle: "Purity in Thought, Speech, and Conduct",
    seoDescription: "Explore biblical purity as a whole-life discipline of the heart, mind, speech, and daily conduct.",
  },
  {
    slug: "hope-that-does-not-make-ashamed",
    title: "Hope That Does Not Make Ashamed",
    scripture: "Romans 5:1-5; Lamentations 3:21-24",
    introduction: "Christian hope is not wishful thinking. It is confidence rooted in God's love, strengthened through trials, and renewed by His daily mercies.",
    sections: [
      { heading: "Hope Grows Through Proven Character", body: "Romans shows a progression from tribulation to patience, experience, and hope. God can use hard seasons to deepen hope rather than destroy it." },
      { heading: "Hope Is Anchored in God's Love", body: "Hope does not make ashamed because God's love is poured into the heart by the Holy Spirit. The believer's confidence rests in divine love, not changing feelings." },
      { heading: "Hope Remembers New Mercies", body: "Lamentations found hope by remembering the Lord's mercies. Memory becomes spiritual warfare when it recalls God's faithfulness in dark seasons." },
    ],
    lessons: ["Hope can grow through suffering.", "God's love anchors the believer's confidence.", "Remembering mercy renews strength.", "Biblical hope is never empty optimism."],
    prayer: "Father, renew my hope in Your love and mercy. Let my trials produce patience, character, and confidence in You.",
    conclusion: "Hope remains because God remains faithful. Let your soul remember His mercies and rise again in expectation.",
    topic: "hope",
    category: "Devotionals",
    tags: ["hope", "mercy", "endurance", "faith"],
    excerpt: "A devotional on biblical hope rooted in God's love, renewed by mercy, and strengthened through trials.",
    seoTitle: "Hope That Does Not Make Ashamed",
    seoDescription: "Discover Christian hope that endures trials, rests in God's love, and is renewed by daily mercies.",
  },
  {
    slug: "unity-without-compromising-truth",
    title: "Unity Without Compromising Truth",
    scripture: "Ephesians 4:1-6; John 17:17-23",
    introduction: "Jesus prayed for unity, but He also prayed that His people would be sanctified by truth. Biblical unity is never built by sacrificing the word of God.",
    sections: [
      { heading: "Unity Requires Humility and Love", body: "Paul calls believers to lowliness, meekness, longsuffering, and forbearance. Unity needs character, not merely shared branding." },
      { heading: "Unity Has Doctrinal Foundations", body: "Ephesians speaks of one Lord, one faith, and one baptism. The church cannot create true unity by ignoring foundational truth." },
      { heading: "Truth Sanctifies the Community", body: "Jesus prayed, 'Sanctify them through thy truth.' A unified church must be a sanctified church, corrected and cleansed by the word." },
    ],
    lessons: ["Unity requires humility and patience.", "Truth is not the enemy of unity.", "False unity avoids correction and eventually collapses.", "The word of God sanctifies the people of God."],
    prayer: "Lord, make Your church one in truth, love, and holiness. Deliver us from pride, division, and compromise.",
    conclusion: "The church must pursue unity with clean doctrine and humble hearts. Truth and love are not rivals in Christ.",
    topic: "unity",
    category: "Ministry Insights",
    tags: ["unity", "truth", "church", "doctrine"],
    excerpt: "A ministry insight on biblical unity that preserves truth, humility, sound doctrine, and sanctified love.",
    seoTitle: "Unity Without Compromising Truth",
    seoDescription: "Understand biblical unity that is rooted in humility, sound doctrine, sanctification, and the truth of God's word.",
  },
];

function buildContent(article: MinistryArticle): string {
  return [
    `## Scripture Foundation\n> ${article.scripture}`,
    `## Introduction\n${article.introduction}`,
    ...article.sections.map((section) => `## ${section.heading}\n${section.body}`),
    `## Key Spiritual Lessons\n${article.lessons.map((lesson) => `- ${lesson}`).join("\n")}`,
    `## Prayer and Reflection\n${article.prayer}`,
    `## Conclusion and Call to Action\n${article.conclusion}\n\nContinue studying the word of God, share this teaching with someone who needs encouragement, and explore more sermons through Temple TV and the JCTM Digital Sanctuary.`,
  ].join("\n\n");
}

function buildSchema(article: MinistryArticle, content: string): string {
  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: article.title,
    description: article.seoDescription,
    author: {
      "@type": "Organization",
      name: AUTHOR,
      url: BASE_URL,
    },
    publisher: {
      "@type": "Organization",
      name: "JCTM Digital Sanctuary",
      logo: { "@type": "ImageObject", url: `${BASE_URL}/opengraph.jpg` },
    },
    mainEntityOfPage: `${BASE_URL}/blog/${article.slug}`,
    url: `${BASE_URL}/blog/${article.slug}`,
    articleSection: article.category,
    keywords: article.tags.join(", "),
    wordCount: content.split(/\s+/).length,
    inLanguage: "en-NG",
  });
}

export async function seedMinistryBlogLibrary(): Promise<void> {
  let inserted = 0;
  for (let index = 0; index < articles.length; index += 1) {
    const article = articles[index];
    const content = buildContent(article);
    const readTime = Math.max(4, Math.ceil(content.split(/\s+/).length / 200));
    const publishedAt = new Date(Date.UTC(2026, 3, 15 - index, 8, 0, 0));
    const result = await pool.query<{ inserted: boolean }>(
      `
        INSERT INTO blog_posts (
          slug, title, excerpt, content, topic, category, tags, author,
          read_time_minutes, featured, seo_title, seo_description,
          meta_title, meta_description, schema_json, published,
          is_published, published_at, generated_at, updated_at
        )
        VALUES (
          $1, $2, $3, $4, $5, $6, $7::text[], $8,
          $9, $10, $11, $12,
          $11, $12, $13, true,
          true, $14, NOW(), NOW()
        )
        ON CONFLICT (slug) DO UPDATE SET
          title = EXCLUDED.title,
          excerpt = EXCLUDED.excerpt,
          content = EXCLUDED.content,
          topic = EXCLUDED.topic,
          category = EXCLUDED.category,
          tags = EXCLUDED.tags,
          author = EXCLUDED.author,
          read_time_minutes = EXCLUDED.read_time_minutes,
          featured = EXCLUDED.featured,
          seo_title = EXCLUDED.seo_title,
          seo_description = EXCLUDED.seo_description,
          meta_title = EXCLUDED.meta_title,
          meta_description = EXCLUDED.meta_description,
          schema_json = EXCLUDED.schema_json,
          published = true,
          is_published = true,
          updated_at = NOW()
        RETURNING (xmax = 0) AS inserted
      `,
      [
        article.slug,
        article.title,
        article.excerpt,
        content,
        article.topic,
        article.category,
        article.tags,
        AUTHOR,
        readTime,
        article.featured ?? false,
        article.seoTitle,
        article.seoDescription,
        buildSchema(article, content),
        publishedAt,
      ],
    );
    if (result.rows[0]?.inserted) inserted += 1;
  }
  logger.info({ total: articles.length, inserted }, "Ministry blog library seeded");
}