import { Router, type IRouter, type Request, type Response } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import galleryRouter from "./gallery";
import sermonsRouter from "./sermons";
import websubRouter from "./websub";
import testimoniesRouter from "./testimonies";
import eventsRouter from "./events";
import givingRouter from "./giving";
import membersRouter from "./members";
import authRouter from "./auth";
import chatRouter from "./chat";
import livestreamRouter from "./livestream";
import altarRouter from "./altar";
import crusadeRouter from "./crusade";
import prayerRouter from "./prayer";
import devotionRouter from "./devotion";
import sermonAssistantRouter from "./sermon-assistant";
import livechatRouter from "./livechat";
import translateRouter from "./translate";
import geoRouter from "./geo";
import visitorsRouter from "./visitors";
import momentsRouter from "./moments";
import aiRouter from "./ai";
import blogRouter from "./blog";
import adminRouter from "./admin";
import adminAuthRouter from "./adminAuth";
import broadcastRouter from "./broadcast";
import pushRouter from "./push";
import conferenceRegistrationRouter from "./conferenceRegistration";
import clientErrorsRouter from "./clientErrors";
import streamRouter from "./stream";
import eventPromotionsRouter from "./eventPromotions";
import videoEventsRouter from "./videoEvents";
import eventNotificationsRouter from "./eventNotifications";
import homeVideosRouter from "./homeVideos";
import monetizationRouter from "./monetization";
import journeyRouter from "./journey";
import conferenceNotifyRouter from "./conferenceNotify";
import conferenceCampaignRouter from "./conferenceCampaign";
import emailUnsubscribeRouter from "./emailUnsubscribe";
import emailAnalyticsRouter from "./emailAnalytics";
import aiIntelligenceRouter from "./aiIntelligence";
import subscribersRouter from "./subscribers";
import bibleRouter from "./bible";
import knowledgeAdminRouter from "./knowledge-admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(galleryRouter);
// websubRouter must come before sermonsRouter — otherwise GET /sermons/websub
// is captured by the /sermons/:id wildcard route in sermonsRouter.
router.use(websubRouter);
router.use(sermonsRouter);
router.use(testimoniesRouter);
router.use(eventsRouter);
router.use(givingRouter);
router.use(membersRouter);
router.use(authRouter);
router.use(chatRouter);
router.use(livestreamRouter);
router.use(altarRouter);
router.use(crusadeRouter);
router.use(prayerRouter);
router.use(devotionRouter);
router.use(sermonAssistantRouter);
router.use(livechatRouter);
router.use(translateRouter);
router.use(geoRouter);
router.use(visitorsRouter);
router.use(momentsRouter);
router.use(aiRouter);
router.use(blogRouter);
router.use(adminRouter);
router.use(adminAuthRouter);
router.use(broadcastRouter);
router.use(pushRouter);
router.use(conferenceRegistrationRouter);
router.use(clientErrorsRouter);
router.use(streamRouter);
router.use(eventPromotionsRouter);
router.use(videoEventsRouter);
router.use(eventNotificationsRouter);
router.use(homeVideosRouter);
router.use(monetizationRouter);
router.use(journeyRouter);
router.use(conferenceNotifyRouter);
router.use(conferenceCampaignRouter);
router.use(emailUnsubscribeRouter);
router.use(emailAnalyticsRouter);
router.use(aiIntelligenceRouter);
router.use(subscribersRouter);
router.use(bibleRouter);
router.use(knowledgeAdminRouter);

// API 404 — any /api/* path that matched no route above returns JSON, never HTML
router.use((_req: Request, res: Response): void => {
  res.status(404).json({ error: "API endpoint not found" });
});

export default router;
